### ISSUE TITLE
[bug] so  many error 

### ISSUE THREAD

**Issue by OmiChrome** [hotsno/mpv-anilist#5] opened 2023-04-05 11:25 UTC
![image](https://user-images.githubusercontent.com/108952834/230066711-8bb7f74e-8e68-4ebb-a6f0-77cb5de25bb7.png)

**Comment by hotsno** [comment] 2023-04-06 07:49
Can you give some more context please?

- Did you follow the installation instructions in the README?
- After you followed those instructions, what else have you done?
- When are those errors occurring? I don't see the command you're running.

**Comment by hotsno** [comment] 2023-04-07 01:31
At the time when I first wrote the code for this project, I didn't have a Windows machine to test on. Now I have one, and I just tested it for the first time and it does work for me. That said, if you're on Windows I would highly consider using [Taiga](https://taiga.moe/) instead. It's open source and great. The reason I created keroro was mainly because I didn't like any of the alternatives on macOS and Linux.

If you still want to try keroro, I really do need more information to help you. A 3-word title and a partial screenshot is not enough... If you want to know what the errors *mean*:
- First section of red is the Discord presence failing to run because you don't have Discord open. This can be ignored and all of the other features should be unaffected.
- 2nd and 3rd sections of red mean that at the path where `update_presence.py` is at, there is no `utils` directory with `mapper.py` inside of it. If you followed the README this shouldn't be the case.
- 4th section is related to the Discord presence and also shouldn't be an issue.

I'm fully willing to help if you respond back with more info, but I'm closing the issue since I've confirmed that keroro does work on Windows and your issue is likely just a setup/config issue.

**Closed as completed by hotsno** 2023-04-07 01:31 UTC

**Comment by OmiChrome** [comment] 2023-04-07 12:01
###### sorry i forgot give info here is some 
- mpv path to execute from terminal :
 " C:\Users\O_0\scoop\apps\mpv-git\current\mpv.com"
- anime path used to test: 
"O:\Videos\[JySzE] Naruto [101-150] [v3] [R2J] [VFR] [Dual Audio] [x264]"
- anime folder :
 "O:\Videos\"

- anilist.lua is copied to : 
 "C:\Users\O_0\scoop\apps\mpv-git\current\portable_config\scripts\anilist.lua"


my question ! 
- how do i watch `w` pressing give me errror 
![image](https://user-images.githubusercontent.com/108952834/230605145-f63deb6c-a288-46f0-b739-3fcb07999615.png)
- what is OFFSET `o` 
- where is my token anilist data stored? 
- do i need to run keroro to watch anime , or mpv is going to trigger kekoro? 


some errror 
```
[anilist] Traceback (most recent call last):
[anilist]   File "C:\Users\O_0\scoop\apps\mpv-git\current\doc\keroro\presence\run_presence.py", line 13, in <module>
[anilist]     RPC = Presence(client_id)
[anilist]           ^^^^^^^^^^^^^^^^^^^
[anilist]   File "C:\Users\O_0\scoop\apps\python\3.11.3\Lib\site-packages\pypresence\presence.py", line 13, in __init__
[anilist]     super().__init__(*args, **kwargs)
[anilist]   File "C:\Users\O_0\scoop\apps\python\3.11.3\Lib\site-packages\pypresence\baseclient.py", line 28, in __init__
[anilist]     raise DiscordNotFound
[anilist] pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
```
modify the discord part so it check if discord is available or not ! 

tried re-installing still things are same

**Comment by hotsno** [comment] 2023-04-09 21:07
This project only allows you to watch anime you have already downloaded. `w naruto` isn't how it's meant to be used. Just type `w` and all of your anime that you have mapped and are with "WATCHING" status on AniList will show up there (if that episode is actually available in your mapped folder).

You are supposed to put AniList token into `config.json` like the instructions say when you run `main.py` for the first time.

The way you're expected to use keroro is like this (I am expecting that you properly set everything up as instructed when first running `main.py`:
- Store your anime in your anime folder. Here's an example of my anime folder.
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/71658949/230796150-f83a550c-853d-4a04-8615-187ba958f8df.png">

- Map your anime folders to AniList entries. `main.py` will ask you to do this automatically when it detects you have a new folder in your anime folder.
- Watch anime by running `main.py`. It should show you a list of things that are mapped and with "WATCHING" status on AniList like this.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/71658949/230796425-4b387d5f-abfe-4c92-ac25-9a8b210fc490.png">

If you want you can send your `config.json`, `map.json` and the first 4 lines of your `anilist.lua` which should be in your `[mpv_path]/scripts` folder. MAKE SURE NOT TO SEND YOUR ANILIST TOKEN which should be in `config.json` if you do this.

**Comment by hotsno** [comment] 2023-04-09 21:19
I've updated the [usage](https://github.com/hotsno/keroro#usage) section in the README, please take a look at it as well.
